---
- name: restart renewal service
  service:
    name: '{{ step_cert_renewal_service }}'
    state: restarted

# Currently unused
#- name: reload affected services
#  command: "{{ step_cert_renewal_reload_command }}"
#  when: step_cert_renewal_reload_command is defined and step_cert_renewal_reload_command | length > 0
#  ignore_errors: true
